// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSVdlj2oymtxDe_iRLO8EMLLXL9N6wHWM',
    appId: '1:667007354691:web:680cd665208a43975651f6',
    messagingSenderId: '667007354691',
    projectId: 'caffedict-gauth',
    authDomain: 'caffedict-gauth.firebaseapp.com',
    storageBucket: 'caffedict-gauth.firebasestorage.app',
    measurementId: 'G-M3C6KHNB18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_knxJoxxsEV0stOaKYeqBakFBsbMbHBA',
    appId: '1:667007354691:android:c7f07497ca57be675651f6',
    messagingSenderId: '667007354691',
    projectId: 'caffedict-gauth',
    storageBucket: 'caffedict-gauth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp0eJUgNFZevWJR1yTks0FJsDRb9Fh0ug',
    appId: '1:667007354691:ios:4bc91c2fc89efbbf5651f6',
    messagingSenderId: '667007354691',
    projectId: 'caffedict-gauth',
    storageBucket: 'caffedict-gauth.firebasestorage.app',
    androidClientId: '667007354691-a34bkc5rj9g05k104rq509gbblhb8k3v.apps.googleusercontent.com',
    iosClientId: '667007354691-gnd6j246kvmp1te0m7nba698r7vmergp.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignApp',
  );

}